version: "3.8"

volumes:
  db_tetris: {}

services:
  db:
    image: mysql:8.0.28-oracle
    hostname: db
    container_name: MySQL_tetris
    restart: unless-stopped
    ports:
      - 3306:3306
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: tetris
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_tetris:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin_tetris
    restart: unless-stopped
    ports:
      - 8079:80
    environment:
      PMA_HOSTS: >-
        db,
      # Example for a separate database for a specific service
      # db-backend2,
      PMA_USER: app
      PMA_PASSWORD: app
      UPLOAD_LIMIT: 1024M
